### PR TITLE
Add info about who to contact in case of missing DLLs

### PR DESCRIPTION
**Pull request by cmb69**

### CODE REVIEW

**Comment by cmb69** [comment]
cc @remicollet

**Comment by remicollet** [comment]
+1

**Comment by remicollet** [comment]
Can even be simply, "These DLL are maintained by the PHP for Windows Team"

**Comment by cmb69** [comment]
Thanks @weltling. Applied as c6823f31d2f0ee94270943f81a6a0288b8c17e3a. I also added further contact info on the teams page (https://github.com/php/web-windows/commit/ded50fd8b29da6a3a4fbe5ac8da833ef1447cc10).

**Comment by weltling** [comment]
Thanks for the quick check, @cmb69!

**Pull request closed without merging**
