### PR TITLE
remove strange max-height

### PR DESCRIPTION
**Pull request by ThaDafinser**
https://pecl.php.net/package-stats.php

So the scrollbar is removed and u got native scrolling

### CODE REVIEW

**Comment by ThaDafinser** [comment]
ping @Tyrael

**Comment by ThaDafinser** [comment]
ping @weltling

**Comment by Tyrael** [comment]
@bjori @pierrejoye what do you think about this? I'm not sure what was the original idea with the overflow here, maybe we wanted visibility for the footer?

**Comment by pierrejoye** [comment]
I cannot remember sorry :)

**Comment by Tyrael** [comment]
ok, then I'm gonna merge it.

**Pull request merged**
